## Introduction to tensors



In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.1


In [3]:
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
vector = tf.constant([1])
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [5]:
matrix = tf.constant([[7, 8, 8], [6, 8, 9]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[7, 8, 8],
       [6, 8, 9]], dtype=int32)>

In [6]:
float_vector = tf.constant([1, 2., 6], dtype=tf.float16)
float_vector

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 6.], dtype=float16)>

In [7]:
float_vector = ["daddy", 1]
float_vector

['daddy', 1]

In [8]:
tensor1 = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
tensor1

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [9]:
tensor2 = tf.constant([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]])
tensor2

<tf.Tensor: shape=(1, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int32)>

In [10]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
changeable_tensor.assign(tf.fill(changeable_tensor.shape, 11))
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11, 11], dtype=int32)>

In [12]:
changeable_tensor[0].assign(0)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 0, 11], dtype=int32)>

In [13]:
gen0 = tf.random.Generator.from_seed(7)
random_1 = gen0.normal(shape=(3, 2))
gen1 = tf.random.Generator.from_seed(7)
random_2 = gen1.normal(shape=(3, 2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

In [14]:
gen2 = tf.random.Generator.from_seed(7)
random_3 = gen2.uniform((3, 2), minval=0, maxval=1, dtype=tf.float32)
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.39932835, 0.7840713 ],
       [0.67880154, 0.73395896],
       [0.5520444 , 0.10948515]], dtype=float32)>

In [15]:
random_4 = tf.random.uniform((3, 2), minval=0, maxval=1, dtype=tf.float32)
random_4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.96978223, 0.5416964 ],
       [0.85054994, 0.77224255],
       [0.70197535, 0.6601857 ]], dtype=float32)>

In [16]:
tf.random.set_seed(7)
random_5 = tf.random.uniform((3, 2), minval=0, maxval=1, dtype=tf.float32)
random_5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8344538 , 0.23336661],
       [0.8796519 , 0.04664922],
       [0.80349684, 0.9420098 ]], dtype=float32)>

In [17]:
tf.random.set_seed(7)
tf.random.shuffle(random_5)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8796519 , 0.04664922],
       [0.80349684, 0.9420098 ],
       [0.8344538 , 0.23336661]], dtype=float32)>

In [18]:
tf.random.set_seed(7)
tf.random.shuffle(random_5)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8796519 , 0.04664922],
       [0.80349684, 0.9420098 ],
       [0.8344538 , 0.23336661]], dtype=float32)>

In [19]:
tf.ones([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [21]:
import numpy as np

In [22]:
np_array1 = np.arange(0, 12, dtype=np.int32).reshape(2, 6)
np_array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)

In [23]:
np_array2 = np.random.randint(0, 10, size=(4, 3), dtype=np.int32)
np_array2

array([[9, 5, 5],
       [1, 1, 1],
       [5, 8, 7],
       [6, 6, 8]], dtype=int32)

In [24]:
tensor_from_np1 = tf.constant(np_array1, shape=(4, 3))
tensor_from_np1

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [25]:
tensor_from_np2 = tf.Variable(np_array2)
tensor_from_np2

<tf.Variable 'Variable:0' shape=(4, 3) dtype=int32, numpy=
array([[9, 5, 5],
       [1, 1, 1],
       [5, 8, 7],
       [6, 6, 8]], dtype=int32)>

In [26]:
np_array1.ndim

2

In [27]:
tensor_from_np1.ndim

2

In [28]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5), dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [29]:
rank_4_tensor[0][1][0]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]), 4, 120)

In [31]:
rank_4_tensor[:1, :2, :2, :2]

<tf.Tensor: shape=(1, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [32]:
rank_4_tensor[:, :, tf.newaxis, :, :,]

<tf.Tensor: shape=(2, 3, 1, 4, 5), dtype=int32, numpy=
array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]],



       [[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]], dtype=int32)>

In [33]:
tf.expand_dims(rank_4_tensor, axis=2)

<tf.Tensor: shape=(2, 3, 1, 4, 5), dtype=int32, numpy=
array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]],



       [[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]]], dtype=int32)>

In [34]:
tensor_new = tf.constant([[1, 2], [3, 4]])
tensor_new + 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [35]:
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
tensor_new = tensor_new + 1
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [37]:
tensor_new1 = tf.Variable([[1, 2], [3, 4]])
tensor_new1 + 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [38]:
tensor_new1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [39]:
tensor_new1.assign_add([[1, 1], [1, 1]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [40]:
tensor_new1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [41]:
tensor_new1.assign_sub([[1, 1], [1, 1]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [42]:
tensor_new1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [43]:
tf.multiply(tensor_new, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [44]:
tensor_new * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [45]:
tf.multiply(tensor_new1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [46]:
tf.multiply(tensor_new, tensor_new1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [47]:
tf.divide(tensor_new, tensor_new1)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.        , 1.5       ],
       [1.33333333, 1.25      ]])>

In [48]:
tensor_new, tensor_new1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [49]:
tf.matmul(tensor_new, tensor_new1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 16],
       [19, 28]], dtype=int32)>

In [50]:
tensor_new * tensor_new1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [51]:
tensor_new @ tensor_new1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 16],
       [19, 28]], dtype=int32)>

In [52]:
tf.transpose(tensor_new)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [3, 5]], dtype=int32)>

In [53]:
tf.reshape(tensor_new1, shape=(1, 4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [54]:
tensor_dtype = tf.constant([2., 5])
tensor_dtype

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [55]:
tensor_dtype = tf.cast(tensor_dtype, dtype=tf.float16)
tensor_dtype

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 5.], dtype=float16)>

In [56]:
tensor_dtype1 = tf.constant([2.9, 5.3])
tensor_dtype1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.9, 5.3], dtype=float32)>

In [57]:
tensor_dtype1 = tf.cast(tensor_dtype1, dtype=tf.int16)
tensor_dtype1

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([2, 5], dtype=int16)>

In [58]:
tensor_dtype1 = tf.constant(["4", "5"])
tensor_dtype1

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'4', b'5'], dtype=object)>

In [59]:
A = tf.constant([-4.6, 6])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-4.6,  6. ], dtype=float32)>

In [60]:
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.6, 6. ], dtype=float32)>

In [61]:
B = tf.constant(np.random.randint(0, 100, size=50))
B

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 0, 53, 25,  8, 13, 64, 89, 77, 56, 83, 27, 58, 71, 70, 18, 95, 43,
       73, 91, 68, 54, 34, 15, 50, 23,  8, 18, 49, 34, 10, 82, 99, 18, 34,
        1, 68, 11, 37, 51,  6, 65, 81, 79, 39, 97, 51, 38, 31, 40, 98])>

In [62]:
tf.size(B).numpy()

50

In [63]:
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [64]:
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [65]:
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [66]:
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int64, numpy=2403>

In [67]:
tf.math.reduce_std(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.951967>

In [68]:
tf.random.set_seed(42)
C = tf.random.uniform([50])
C

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [69]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [70]:
C[tf.argmax(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [71]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [72]:
C[tf.argmin(C)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [73]:
tf.random.set_seed(42)
D = tf.random.uniform([3, 14])
D

<tf.Tensor: shape=(3, 14), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 ],
       [0.5746088 , 0.8996835 , 0.00946367, 0.5212307 , 0.6345445 ,
        0.1993283 , 0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
        0.6602763 , 0.33695042, 0.60141766, 0.21062577],
       [0.8527372 , 0.44062173, 0.9485276 , 0.23752594, 0.81179297,
        0.5263394 , 0.494308  , 0.21612847, 0.8457197 , 0.8718841 ,
        0.3083862 , 0.6868038 , 0.23764038, 0.7817228 ]], dtype=float32)>

In [74]:
tf.reduce_max(D[2])

<tf.Tensor: shape=(), dtype=float32, numpy=0.9485276>

In [75]:
tf.random.set_seed(42)
E = tf.random.uniform([1, 1, 14])
E

<tf.Tensor: shape=(1, 1, 14), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 ]]], dtype=float32)>

In [76]:
tf.squeeze(E)

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 ], dtype=float32)>

In [78]:
list1 = [0, 1, 2, 3]

In [85]:
tf.one_hot(list1, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [84]:
tf.one_hot(list1, 6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [83]:
tf.one_hot(list1, 4, "Yes", "No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

In [87]:
F = tf.range(1, 10)
F

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [88]:
tf.square(F)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [89]:
tf.sqrt(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [92]:
tf.math.log(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [94]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]